// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bitsnake-server/internal/ent/matches"
	"bitsnake-server/internal/ent/matchresults"
	"bitsnake-server/internal/ent/predicate"
	"bitsnake-server/internal/ent/users"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MatchesQuery is the builder for querying Matches entities.
type MatchesQuery struct {
	config
	ctx              *QueryContext
	order            []matches.OrderOption
	inters           []Interceptor
	predicates       []predicate.Matches
	withMatchResults *MatchResultsQuery
	withUser         *UsersQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MatchesQuery builder.
func (mq *MatchesQuery) Where(ps ...predicate.Matches) *MatchesQuery {
	mq.predicates = append(mq.predicates, ps...)
	return mq
}

// Limit the number of records to be returned by this query.
func (mq *MatchesQuery) Limit(limit int) *MatchesQuery {
	mq.ctx.Limit = &limit
	return mq
}

// Offset to start from.
func (mq *MatchesQuery) Offset(offset int) *MatchesQuery {
	mq.ctx.Offset = &offset
	return mq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mq *MatchesQuery) Unique(unique bool) *MatchesQuery {
	mq.ctx.Unique = &unique
	return mq
}

// Order specifies how the records should be ordered.
func (mq *MatchesQuery) Order(o ...matches.OrderOption) *MatchesQuery {
	mq.order = append(mq.order, o...)
	return mq
}

// QueryMatchResults chains the current query on the "match_results" edge.
func (mq *MatchesQuery) QueryMatchResults() *MatchResultsQuery {
	query := (&MatchResultsClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(matches.Table, matches.FieldID, selector),
			sqlgraph.To(matchresults.Table, matchresults.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, matches.MatchResultsTable, matches.MatchResultsColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (mq *MatchesQuery) QueryUser() *UsersQuery {
	query := (&UsersClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(matches.Table, matches.FieldID, selector),
			sqlgraph.To(users.Table, users.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, matches.UserTable, matches.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Matches entity from the query.
// Returns a *NotFoundError when no Matches was found.
func (mq *MatchesQuery) First(ctx context.Context) (*Matches, error) {
	nodes, err := mq.Limit(1).All(setContextOp(ctx, mq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{matches.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mq *MatchesQuery) FirstX(ctx context.Context) *Matches {
	node, err := mq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Matches ID from the query.
// Returns a *NotFoundError when no Matches ID was found.
func (mq *MatchesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(1).IDs(setContextOp(ctx, mq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{matches.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mq *MatchesQuery) FirstIDX(ctx context.Context) int {
	id, err := mq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Matches entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Matches entity is found.
// Returns a *NotFoundError when no Matches entities are found.
func (mq *MatchesQuery) Only(ctx context.Context) (*Matches, error) {
	nodes, err := mq.Limit(2).All(setContextOp(ctx, mq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{matches.Label}
	default:
		return nil, &NotSingularError{matches.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mq *MatchesQuery) OnlyX(ctx context.Context) *Matches {
	node, err := mq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Matches ID in the query.
// Returns a *NotSingularError when more than one Matches ID is found.
// Returns a *NotFoundError when no entities are found.
func (mq *MatchesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(2).IDs(setContextOp(ctx, mq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{matches.Label}
	default:
		err = &NotSingularError{matches.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mq *MatchesQuery) OnlyIDX(ctx context.Context) int {
	id, err := mq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MatchesSlice.
func (mq *MatchesQuery) All(ctx context.Context) ([]*Matches, error) {
	ctx = setContextOp(ctx, mq.ctx, ent.OpQueryAll)
	if err := mq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Matches, *MatchesQuery]()
	return withInterceptors[[]*Matches](ctx, mq, qr, mq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mq *MatchesQuery) AllX(ctx context.Context) []*Matches {
	nodes, err := mq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Matches IDs.
func (mq *MatchesQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mq.ctx.Unique == nil && mq.path != nil {
		mq.Unique(true)
	}
	ctx = setContextOp(ctx, mq.ctx, ent.OpQueryIDs)
	if err = mq.Select(matches.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mq *MatchesQuery) IDsX(ctx context.Context) []int {
	ids, err := mq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mq *MatchesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mq.ctx, ent.OpQueryCount)
	if err := mq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mq, querierCount[*MatchesQuery](), mq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mq *MatchesQuery) CountX(ctx context.Context) int {
	count, err := mq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mq *MatchesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mq.ctx, ent.OpQueryExist)
	switch _, err := mq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mq *MatchesQuery) ExistX(ctx context.Context) bool {
	exist, err := mq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MatchesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mq *MatchesQuery) Clone() *MatchesQuery {
	if mq == nil {
		return nil
	}
	return &MatchesQuery{
		config:           mq.config,
		ctx:              mq.ctx.Clone(),
		order:            append([]matches.OrderOption{}, mq.order...),
		inters:           append([]Interceptor{}, mq.inters...),
		predicates:       append([]predicate.Matches{}, mq.predicates...),
		withMatchResults: mq.withMatchResults.Clone(),
		withUser:         mq.withUser.Clone(),
		// clone intermediate query.
		sql:  mq.sql.Clone(),
		path: mq.path,
	}
}

// WithMatchResults tells the query-builder to eager-load the nodes that are connected to
// the "match_results" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *MatchesQuery) WithMatchResults(opts ...func(*MatchResultsQuery)) *MatchesQuery {
	query := (&MatchResultsClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withMatchResults = query
	return mq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *MatchesQuery) WithUser(opts ...func(*UsersQuery)) *MatchesQuery {
	query := (&UsersClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withUser = query
	return mq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GameHashID string `json:"game_hash_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Matches.Query().
//		GroupBy(matches.FieldGameHashID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mq *MatchesQuery) GroupBy(field string, fields ...string) *MatchesGroupBy {
	mq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MatchesGroupBy{build: mq}
	grbuild.flds = &mq.ctx.Fields
	grbuild.label = matches.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GameHashID string `json:"game_hash_id,omitempty"`
//	}
//
//	client.Matches.Query().
//		Select(matches.FieldGameHashID).
//		Scan(ctx, &v)
func (mq *MatchesQuery) Select(fields ...string) *MatchesSelect {
	mq.ctx.Fields = append(mq.ctx.Fields, fields...)
	sbuild := &MatchesSelect{MatchesQuery: mq}
	sbuild.label = matches.Label
	sbuild.flds, sbuild.scan = &mq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MatchesSelect configured with the given aggregations.
func (mq *MatchesQuery) Aggregate(fns ...AggregateFunc) *MatchesSelect {
	return mq.Select().Aggregate(fns...)
}

func (mq *MatchesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mq); err != nil {
				return err
			}
		}
	}
	for _, f := range mq.ctx.Fields {
		if !matches.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mq.path != nil {
		prev, err := mq.path(ctx)
		if err != nil {
			return err
		}
		mq.sql = prev
	}
	return nil
}

func (mq *MatchesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Matches, error) {
	var (
		nodes       = []*Matches{}
		withFKs     = mq.withFKs
		_spec       = mq.querySpec()
		loadedTypes = [2]bool{
			mq.withMatchResults != nil,
			mq.withUser != nil,
		}
	)
	if mq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, matches.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Matches).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Matches{config: mq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mq.withMatchResults; query != nil {
		if err := mq.loadMatchResults(ctx, query, nodes,
			func(n *Matches) { n.Edges.MatchResults = []*MatchResults{} },
			func(n *Matches, e *MatchResults) { n.Edges.MatchResults = append(n.Edges.MatchResults, e) }); err != nil {
			return nil, err
		}
	}
	if query := mq.withUser; query != nil {
		if err := mq.loadUser(ctx, query, nodes, nil,
			func(n *Matches, e *Users) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mq *MatchesQuery) loadMatchResults(ctx context.Context, query *MatchResultsQuery, nodes []*Matches, init func(*Matches), assign func(*Matches, *MatchResults)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Matches)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.MatchResults(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(matches.MatchResultsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.matches_match_results
		if fk == nil {
			return fmt.Errorf(`foreign-key "matches_match_results" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "matches_match_results" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (mq *MatchesQuery) loadUser(ctx context.Context, query *UsersQuery, nodes []*Matches, init func(*Matches), assign func(*Matches, *Users)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Matches)
	for i := range nodes {
		if nodes[i].users_matches == nil {
			continue
		}
		fk := *nodes[i].users_matches
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(users.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "users_matches" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mq *MatchesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mq.querySpec()
	_spec.Node.Columns = mq.ctx.Fields
	if len(mq.ctx.Fields) > 0 {
		_spec.Unique = mq.ctx.Unique != nil && *mq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mq.driver, _spec)
}

func (mq *MatchesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(matches.Table, matches.Columns, sqlgraph.NewFieldSpec(matches.FieldID, field.TypeInt))
	_spec.From = mq.sql
	if unique := mq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mq.path != nil {
		_spec.Unique = true
	}
	if fields := mq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, matches.FieldID)
		for i := range fields {
			if fields[i] != matches.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mq *MatchesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mq.driver.Dialect())
	t1 := builder.Table(matches.Table)
	columns := mq.ctx.Fields
	if len(columns) == 0 {
		columns = matches.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mq.sql != nil {
		selector = mq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mq.ctx.Unique != nil && *mq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mq.predicates {
		p(selector)
	}
	for _, p := range mq.order {
		p(selector)
	}
	if offset := mq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MatchesGroupBy is the group-by builder for Matches entities.
type MatchesGroupBy struct {
	selector
	build *MatchesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mgb *MatchesGroupBy) Aggregate(fns ...AggregateFunc) *MatchesGroupBy {
	mgb.fns = append(mgb.fns, fns...)
	return mgb
}

// Scan applies the selector query and scans the result into the given value.
func (mgb *MatchesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mgb.build.ctx, ent.OpQueryGroupBy)
	if err := mgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MatchesQuery, *MatchesGroupBy](ctx, mgb.build, mgb, mgb.build.inters, v)
}

func (mgb *MatchesGroupBy) sqlScan(ctx context.Context, root *MatchesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mgb.fns))
	for _, fn := range mgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mgb.flds)+len(mgb.fns))
		for _, f := range *mgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MatchesSelect is the builder for selecting fields of Matches entities.
type MatchesSelect struct {
	*MatchesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ms *MatchesSelect) Aggregate(fns ...AggregateFunc) *MatchesSelect {
	ms.fns = append(ms.fns, fns...)
	return ms
}

// Scan applies the selector query and scans the result into the given value.
func (ms *MatchesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ms.ctx, ent.OpQuerySelect)
	if err := ms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MatchesQuery, *MatchesSelect](ctx, ms.MatchesQuery, ms, ms.inters, v)
}

func (ms *MatchesSelect) sqlScan(ctx context.Context, root *MatchesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ms.fns))
	for _, fn := range ms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
