// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bitsnake-server/internal/ent/matches"
	"bitsnake-server/internal/ent/matchresults"
	"bitsnake-server/internal/ent/predicate"
	"bitsnake-server/internal/ent/users"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MatchResultsQuery is the builder for querying MatchResults entities.
type MatchResultsQuery struct {
	config
	ctx        *QueryContext
	order      []matchresults.OrderOption
	inters     []Interceptor
	predicates []predicate.MatchResults
	withUser   *UsersQuery
	withMatch  *MatchesQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MatchResultsQuery builder.
func (mrq *MatchResultsQuery) Where(ps ...predicate.MatchResults) *MatchResultsQuery {
	mrq.predicates = append(mrq.predicates, ps...)
	return mrq
}

// Limit the number of records to be returned by this query.
func (mrq *MatchResultsQuery) Limit(limit int) *MatchResultsQuery {
	mrq.ctx.Limit = &limit
	return mrq
}

// Offset to start from.
func (mrq *MatchResultsQuery) Offset(offset int) *MatchResultsQuery {
	mrq.ctx.Offset = &offset
	return mrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mrq *MatchResultsQuery) Unique(unique bool) *MatchResultsQuery {
	mrq.ctx.Unique = &unique
	return mrq
}

// Order specifies how the records should be ordered.
func (mrq *MatchResultsQuery) Order(o ...matchresults.OrderOption) *MatchResultsQuery {
	mrq.order = append(mrq.order, o...)
	return mrq
}

// QueryUser chains the current query on the "user" edge.
func (mrq *MatchResultsQuery) QueryUser() *UsersQuery {
	query := (&UsersClient{config: mrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(matchresults.Table, matchresults.FieldID, selector),
			sqlgraph.To(users.Table, users.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, matchresults.UserTable, matchresults.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(mrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMatch chains the current query on the "match" edge.
func (mrq *MatchResultsQuery) QueryMatch() *MatchesQuery {
	query := (&MatchesClient{config: mrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(matchresults.Table, matchresults.FieldID, selector),
			sqlgraph.To(matches.Table, matches.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, matchresults.MatchTable, matchresults.MatchColumn),
		)
		fromU = sqlgraph.SetNeighbors(mrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MatchResults entity from the query.
// Returns a *NotFoundError when no MatchResults was found.
func (mrq *MatchResultsQuery) First(ctx context.Context) (*MatchResults, error) {
	nodes, err := mrq.Limit(1).All(setContextOp(ctx, mrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{matchresults.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mrq *MatchResultsQuery) FirstX(ctx context.Context) *MatchResults {
	node, err := mrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MatchResults ID from the query.
// Returns a *NotFoundError when no MatchResults ID was found.
func (mrq *MatchResultsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mrq.Limit(1).IDs(setContextOp(ctx, mrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{matchresults.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mrq *MatchResultsQuery) FirstIDX(ctx context.Context) int {
	id, err := mrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MatchResults entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MatchResults entity is found.
// Returns a *NotFoundError when no MatchResults entities are found.
func (mrq *MatchResultsQuery) Only(ctx context.Context) (*MatchResults, error) {
	nodes, err := mrq.Limit(2).All(setContextOp(ctx, mrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{matchresults.Label}
	default:
		return nil, &NotSingularError{matchresults.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mrq *MatchResultsQuery) OnlyX(ctx context.Context) *MatchResults {
	node, err := mrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MatchResults ID in the query.
// Returns a *NotSingularError when more than one MatchResults ID is found.
// Returns a *NotFoundError when no entities are found.
func (mrq *MatchResultsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mrq.Limit(2).IDs(setContextOp(ctx, mrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{matchresults.Label}
	default:
		err = &NotSingularError{matchresults.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mrq *MatchResultsQuery) OnlyIDX(ctx context.Context) int {
	id, err := mrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MatchResultsSlice.
func (mrq *MatchResultsQuery) All(ctx context.Context) ([]*MatchResults, error) {
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryAll)
	if err := mrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MatchResults, *MatchResultsQuery]()
	return withInterceptors[[]*MatchResults](ctx, mrq, qr, mrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mrq *MatchResultsQuery) AllX(ctx context.Context) []*MatchResults {
	nodes, err := mrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MatchResults IDs.
func (mrq *MatchResultsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mrq.ctx.Unique == nil && mrq.path != nil {
		mrq.Unique(true)
	}
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryIDs)
	if err = mrq.Select(matchresults.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mrq *MatchResultsQuery) IDsX(ctx context.Context) []int {
	ids, err := mrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mrq *MatchResultsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryCount)
	if err := mrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mrq, querierCount[*MatchResultsQuery](), mrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mrq *MatchResultsQuery) CountX(ctx context.Context) int {
	count, err := mrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mrq *MatchResultsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryExist)
	switch _, err := mrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mrq *MatchResultsQuery) ExistX(ctx context.Context) bool {
	exist, err := mrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MatchResultsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mrq *MatchResultsQuery) Clone() *MatchResultsQuery {
	if mrq == nil {
		return nil
	}
	return &MatchResultsQuery{
		config:     mrq.config,
		ctx:        mrq.ctx.Clone(),
		order:      append([]matchresults.OrderOption{}, mrq.order...),
		inters:     append([]Interceptor{}, mrq.inters...),
		predicates: append([]predicate.MatchResults{}, mrq.predicates...),
		withUser:   mrq.withUser.Clone(),
		withMatch:  mrq.withMatch.Clone(),
		// clone intermediate query.
		sql:  mrq.sql.Clone(),
		path: mrq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (mrq *MatchResultsQuery) WithUser(opts ...func(*UsersQuery)) *MatchResultsQuery {
	query := (&UsersClient{config: mrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mrq.withUser = query
	return mrq
}

// WithMatch tells the query-builder to eager-load the nodes that are connected to
// the "match" edge. The optional arguments are used to configure the query builder of the edge.
func (mrq *MatchResultsQuery) WithMatch(opts ...func(*MatchesQuery)) *MatchResultsQuery {
	query := (&MatchesClient{config: mrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mrq.withMatch = query
	return mrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Kills int `json:"kills,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MatchResults.Query().
//		GroupBy(matchresults.FieldKills).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mrq *MatchResultsQuery) GroupBy(field string, fields ...string) *MatchResultsGroupBy {
	mrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MatchResultsGroupBy{build: mrq}
	grbuild.flds = &mrq.ctx.Fields
	grbuild.label = matchresults.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Kills int `json:"kills,omitempty"`
//	}
//
//	client.MatchResults.Query().
//		Select(matchresults.FieldKills).
//		Scan(ctx, &v)
func (mrq *MatchResultsQuery) Select(fields ...string) *MatchResultsSelect {
	mrq.ctx.Fields = append(mrq.ctx.Fields, fields...)
	sbuild := &MatchResultsSelect{MatchResultsQuery: mrq}
	sbuild.label = matchresults.Label
	sbuild.flds, sbuild.scan = &mrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MatchResultsSelect configured with the given aggregations.
func (mrq *MatchResultsQuery) Aggregate(fns ...AggregateFunc) *MatchResultsSelect {
	return mrq.Select().Aggregate(fns...)
}

func (mrq *MatchResultsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mrq); err != nil {
				return err
			}
		}
	}
	for _, f := range mrq.ctx.Fields {
		if !matchresults.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mrq.path != nil {
		prev, err := mrq.path(ctx)
		if err != nil {
			return err
		}
		mrq.sql = prev
	}
	return nil
}

func (mrq *MatchResultsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MatchResults, error) {
	var (
		nodes       = []*MatchResults{}
		withFKs     = mrq.withFKs
		_spec       = mrq.querySpec()
		loadedTypes = [2]bool{
			mrq.withUser != nil,
			mrq.withMatch != nil,
		}
	)
	if mrq.withUser != nil || mrq.withMatch != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, matchresults.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MatchResults).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MatchResults{config: mrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mrq.withUser; query != nil {
		if err := mrq.loadUser(ctx, query, nodes, nil,
			func(n *MatchResults, e *Users) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := mrq.withMatch; query != nil {
		if err := mrq.loadMatch(ctx, query, nodes, nil,
			func(n *MatchResults, e *Matches) { n.Edges.Match = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mrq *MatchResultsQuery) loadUser(ctx context.Context, query *UsersQuery, nodes []*MatchResults, init func(*MatchResults), assign func(*MatchResults, *Users)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MatchResults)
	for i := range nodes {
		if nodes[i].users_match_results == nil {
			continue
		}
		fk := *nodes[i].users_match_results
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(users.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "users_match_results" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mrq *MatchResultsQuery) loadMatch(ctx context.Context, query *MatchesQuery, nodes []*MatchResults, init func(*MatchResults), assign func(*MatchResults, *Matches)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MatchResults)
	for i := range nodes {
		if nodes[i].matches_match_results == nil {
			continue
		}
		fk := *nodes[i].matches_match_results
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(matches.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "matches_match_results" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mrq *MatchResultsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mrq.querySpec()
	_spec.Node.Columns = mrq.ctx.Fields
	if len(mrq.ctx.Fields) > 0 {
		_spec.Unique = mrq.ctx.Unique != nil && *mrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mrq.driver, _spec)
}

func (mrq *MatchResultsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(matchresults.Table, matchresults.Columns, sqlgraph.NewFieldSpec(matchresults.FieldID, field.TypeInt))
	_spec.From = mrq.sql
	if unique := mrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mrq.path != nil {
		_spec.Unique = true
	}
	if fields := mrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, matchresults.FieldID)
		for i := range fields {
			if fields[i] != matchresults.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mrq *MatchResultsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mrq.driver.Dialect())
	t1 := builder.Table(matchresults.Table)
	columns := mrq.ctx.Fields
	if len(columns) == 0 {
		columns = matchresults.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mrq.sql != nil {
		selector = mrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mrq.ctx.Unique != nil && *mrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mrq.predicates {
		p(selector)
	}
	for _, p := range mrq.order {
		p(selector)
	}
	if offset := mrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MatchResultsGroupBy is the group-by builder for MatchResults entities.
type MatchResultsGroupBy struct {
	selector
	build *MatchResultsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mrgb *MatchResultsGroupBy) Aggregate(fns ...AggregateFunc) *MatchResultsGroupBy {
	mrgb.fns = append(mrgb.fns, fns...)
	return mrgb
}

// Scan applies the selector query and scans the result into the given value.
func (mrgb *MatchResultsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrgb.build.ctx, ent.OpQueryGroupBy)
	if err := mrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MatchResultsQuery, *MatchResultsGroupBy](ctx, mrgb.build, mrgb, mrgb.build.inters, v)
}

func (mrgb *MatchResultsGroupBy) sqlScan(ctx context.Context, root *MatchResultsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mrgb.fns))
	for _, fn := range mrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mrgb.flds)+len(mrgb.fns))
		for _, f := range *mrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MatchResultsSelect is the builder for selecting fields of MatchResults entities.
type MatchResultsSelect struct {
	*MatchResultsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mrs *MatchResultsSelect) Aggregate(fns ...AggregateFunc) *MatchResultsSelect {
	mrs.fns = append(mrs.fns, fns...)
	return mrs
}

// Scan applies the selector query and scans the result into the given value.
func (mrs *MatchResultsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrs.ctx, ent.OpQuerySelect)
	if err := mrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MatchResultsQuery, *MatchResultsSelect](ctx, mrs.MatchResultsQuery, mrs, mrs.inters, v)
}

func (mrs *MatchResultsSelect) sqlScan(ctx context.Context, root *MatchResultsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mrs.fns))
	for _, fn := range mrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
