// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bitsnake-server/internal/ent/paymentverifications"
	"bitsnake-server/internal/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentVerificationsDelete is the builder for deleting a PaymentVerifications entity.
type PaymentVerificationsDelete struct {
	config
	hooks    []Hook
	mutation *PaymentVerificationsMutation
}

// Where appends a list predicates to the PaymentVerificationsDelete builder.
func (pvd *PaymentVerificationsDelete) Where(ps ...predicate.PaymentVerifications) *PaymentVerificationsDelete {
	pvd.mutation.Where(ps...)
	return pvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pvd *PaymentVerificationsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pvd.sqlExec, pvd.mutation, pvd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pvd *PaymentVerificationsDelete) ExecX(ctx context.Context) int {
	n, err := pvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pvd *PaymentVerificationsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentverifications.Table, sqlgraph.NewFieldSpec(paymentverifications.FieldID, field.TypeInt))
	if ps := pvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pvd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pvd.mutation.done = true
	return affected, err
}

// PaymentVerificationsDeleteOne is the builder for deleting a single PaymentVerifications entity.
type PaymentVerificationsDeleteOne struct {
	pvd *PaymentVerificationsDelete
}

// Where appends a list predicates to the PaymentVerificationsDelete builder.
func (pvdo *PaymentVerificationsDeleteOne) Where(ps ...predicate.PaymentVerifications) *PaymentVerificationsDeleteOne {
	pvdo.pvd.mutation.Where(ps...)
	return pvdo
}

// Exec executes the deletion query.
func (pvdo *PaymentVerificationsDeleteOne) Exec(ctx context.Context) error {
	n, err := pvdo.pvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentverifications.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pvdo *PaymentVerificationsDeleteOne) ExecX(ctx context.Context) {
	if err := pvdo.Exec(ctx); err != nil {
		panic(err)
	}
}
