// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bitsnake-server/internal/ent/matches"
	"bitsnake-server/internal/ent/matchresults"
	"bitsnake-server/internal/ent/paymentverifications"
	"bitsnake-server/internal/ent/schema"
	"bitsnake-server/internal/ent/users"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	matchresultsFields := schema.MatchResults{}.Fields()
	_ = matchresultsFields
	// matchresultsDescKills is the schema descriptor for kills field.
	matchresultsDescKills := matchresultsFields[0].Descriptor()
	// matchresults.DefaultKills holds the default value on creation for the kills field.
	matchresults.DefaultKills = matchresultsDescKills.Default.(int)
	// matchresultsDescIsWinner is the schema descriptor for is_winner field.
	matchresultsDescIsWinner := matchresultsFields[1].Descriptor()
	// matchresults.DefaultIsWinner holds the default value on creation for the is_winner field.
	matchresults.DefaultIsWinner = matchresultsDescIsWinner.Default.(bool)
	matchesFields := schema.Matches{}.Fields()
	_ = matchesFields
	// matchesDescGameHashID is the schema descriptor for game_hash_id field.
	matchesDescGameHashID := matchesFields[0].Descriptor()
	// matches.GameHashIDValidator is a validator for the "game_hash_id" field. It is called by the builders before save.
	matches.GameHashIDValidator = matchesDescGameHashID.Validators[0].(func(string) error)
	// matchesDescWalletAddress is the schema descriptor for wallet_address field.
	matchesDescWalletAddress := matchesFields[2].Descriptor()
	// matches.WalletAddressValidator is a validator for the "wallet_address" field. It is called by the builders before save.
	matches.WalletAddressValidator = matchesDescWalletAddress.Validators[0].(func(string) error)
	// matchesDescTransactionHash is the schema descriptor for transaction_hash field.
	matchesDescTransactionHash := matchesFields[3].Descriptor()
	// matches.TransactionHashValidator is a validator for the "transaction_hash" field. It is called by the builders before save.
	matches.TransactionHashValidator = matchesDescTransactionHash.Validators[0].(func(string) error)
	// matchesDescCreatedAt is the schema descriptor for created_at field.
	matchesDescCreatedAt := matchesFields[4].Descriptor()
	// matches.DefaultCreatedAt holds the default value on creation for the created_at field.
	matches.DefaultCreatedAt = matchesDescCreatedAt.Default.(func() time.Time)
	paymentverificationsFields := schema.PaymentVerifications{}.Fields()
	_ = paymentverificationsFields
	// paymentverificationsDescWalletAddress is the schema descriptor for wallet_address field.
	paymentverificationsDescWalletAddress := paymentverificationsFields[1].Descriptor()
	// paymentverifications.WalletAddressValidator is a validator for the "wallet_address" field. It is called by the builders before save.
	paymentverifications.WalletAddressValidator = func() func(string) error {
		validators := paymentverificationsDescWalletAddress.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(wallet_address string) error {
			for _, fn := range fns {
				if err := fn(wallet_address); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// paymentverificationsDescTransactionHash is the schema descriptor for transaction_hash field.
	paymentverificationsDescTransactionHash := paymentverificationsFields[3].Descriptor()
	// paymentverifications.TransactionHashValidator is a validator for the "transaction_hash" field. It is called by the builders before save.
	paymentverifications.TransactionHashValidator = paymentverificationsDescTransactionHash.Validators[0].(func(string) error)
	// paymentverificationsDescAccessGranted is the schema descriptor for access_granted field.
	paymentverificationsDescAccessGranted := paymentverificationsFields[5].Descriptor()
	// paymentverifications.DefaultAccessGranted holds the default value on creation for the access_granted field.
	paymentverifications.DefaultAccessGranted = paymentverificationsDescAccessGranted.Default.(bool)
	// paymentverificationsDescCreatedAt is the schema descriptor for created_at field.
	paymentverificationsDescCreatedAt := paymentverificationsFields[6].Descriptor()
	// paymentverifications.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentverifications.DefaultCreatedAt = paymentverificationsDescCreatedAt.Default.(func() time.Time)
	usersFields := schema.Users{}.Fields()
	_ = usersFields
	// usersDescWalletAddress is the schema descriptor for wallet_address field.
	usersDescWalletAddress := usersFields[0].Descriptor()
	// users.WalletAddressValidator is a validator for the "wallet_address" field. It is called by the builders before save.
	users.WalletAddressValidator = usersDescWalletAddress.Validators[0].(func(string) error)
	// usersDescHasAccess is the schema descriptor for has_access field.
	usersDescHasAccess := usersFields[1].Descriptor()
	// users.DefaultHasAccess holds the default value on creation for the has_access field.
	users.DefaultHasAccess = usersDescHasAccess.Default.(bool)
}
