// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bitsnake-server/internal/ent/users"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Users is the model entity for the Users schema.
type Users struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// WalletAddress holds the value of the "wallet_address" field.
	WalletAddress string `json:"wallet_address,omitempty"`
	// Whether the user has service access
	HasAccess bool `json:"has_access,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsersQuery when eager-loading is set.
	Edges        UsersEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsersEdges holds the relations/edges for other nodes in the graph.
type UsersEdges struct {
	// Matches holds the value of the matches edge.
	Matches []*Matches `json:"matches,omitempty"`
	// MatchResults holds the value of the match_results edge.
	MatchResults []*MatchResults `json:"match_results,omitempty"`
	// Payment verification records for this user
	Payments []*PaymentVerifications `json:"payments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// MatchesOrErr returns the Matches value or an error if the edge
// was not loaded in eager-loading.
func (e UsersEdges) MatchesOrErr() ([]*Matches, error) {
	if e.loadedTypes[0] {
		return e.Matches, nil
	}
	return nil, &NotLoadedError{edge: "matches"}
}

// MatchResultsOrErr returns the MatchResults value or an error if the edge
// was not loaded in eager-loading.
func (e UsersEdges) MatchResultsOrErr() ([]*MatchResults, error) {
	if e.loadedTypes[1] {
		return e.MatchResults, nil
	}
	return nil, &NotLoadedError{edge: "match_results"}
}

// PaymentsOrErr returns the Payments value or an error if the edge
// was not loaded in eager-loading.
func (e UsersEdges) PaymentsOrErr() ([]*PaymentVerifications, error) {
	if e.loadedTypes[2] {
		return e.Payments, nil
	}
	return nil, &NotLoadedError{edge: "payments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Users) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case users.FieldHasAccess:
			values[i] = new(sql.NullBool)
		case users.FieldID:
			values[i] = new(sql.NullInt64)
		case users.FieldWalletAddress:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Users fields.
func (u *Users) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case users.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			u.ID = int(value.Int64)
		case users.FieldWalletAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_address", values[i])
			} else if value.Valid {
				u.WalletAddress = value.String
			}
		case users.FieldHasAccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_access", values[i])
			} else if value.Valid {
				u.HasAccess = value.Bool
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Users.
// This includes values selected through modifiers, order, etc.
func (u *Users) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// QueryMatches queries the "matches" edge of the Users entity.
func (u *Users) QueryMatches() *MatchesQuery {
	return NewUsersClient(u.config).QueryMatches(u)
}

// QueryMatchResults queries the "match_results" edge of the Users entity.
func (u *Users) QueryMatchResults() *MatchResultsQuery {
	return NewUsersClient(u.config).QueryMatchResults(u)
}

// QueryPayments queries the "payments" edge of the Users entity.
func (u *Users) QueryPayments() *PaymentVerificationsQuery {
	return NewUsersClient(u.config).QueryPayments(u)
}

// Update returns a builder for updating this Users.
// Note that you need to call Users.Unwrap() before calling this method if this Users
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *Users) Update() *UsersUpdateOne {
	return NewUsersClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the Users entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *Users) Unwrap() *Users {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: Users is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *Users) String() string {
	var builder strings.Builder
	builder.WriteString("Users(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("wallet_address=")
	builder.WriteString(u.WalletAddress)
	builder.WriteString(", ")
	builder.WriteString("has_access=")
	builder.WriteString(fmt.Sprintf("%v", u.HasAccess))
	builder.WriteByte(')')
	return builder.String()
}

// UsersSlice is a parsable slice of Users.
type UsersSlice []*Users
