// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MatchResults is the predicate function for matchresults builders.
type MatchResults func(*sql.Selector)

// Matches is the predicate function for matches builders.
type Matches func(*sql.Selector)

// PaymentVerifications is the predicate function for paymentverifications builders.
type PaymentVerifications func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
